config/routes.rb
Eventica::Application.routes.draw do
  
  resources :events, :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/steps', to: 'static_pages#steps'
  match '/about', to: 'static_pages#about'
  match '/contacts', to: 'static_pages#contacts'

  match '/create', to: 'events#new'

  match '/myevents', to: 'users#show'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  user_id     :integer
#  description :string(255)
#  venue       :string(255)
#  start_date  :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  end_date    :datetime
#

class Event < ActiveRecord::Base
  attr_accessible :start_date, :end_date, :description, :title, :venue
  belongs_to :user

  validates :user_id, presence: true
  validates :title, presence: true
  validates :venue, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true


  default_scope order: 'events.start_date DESC'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  has_many :events, dependent: :destroy

  before_save {|user| user.email = email.downcase}
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
  					format: {with: VALID_EMAIL_REGEX},
  					uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64      
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.order(:title)
  end

  def create
    @event = current_user.events.build(params[:event])

    if @event.save
      flash[:success] = "Event created!"
      redirect_to current_user
    else
      flash.now[:error] = "Event was not created created!"
      render :new     
    end
  end
  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    if signed_in?
      @event = Event.new
    else
      flash.now[:error] = "You need to sign in"
      redirect_to signin_path
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new		
	end

	def create
		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to user
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end		
	end

	def destroy
		sign_out
		redirect_to root_url		
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@events = Event.order(:title)
  end

  def steps
  end

  def about  	
  end

  def contacts  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if signed_in?
      flash.now[:success] = "You are logged in"
      redirect_to current_user
    end
  	@user = User.new
  end

  def show
    if current_user
      @user = current_user
    else
      @user = User.find(params[:id])
    end
    @events = @user.events.paginate(page: params[:page])
  end

  def create
    @user = User.new(params[:user])
  	if @user.save
      sign_in @user
  		flash[:success] = "Welcome to the Eventr! Here you can create your own events"
  		redirect_to @user
  	else
  		render 'new'
  	end
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies[:remember_token] = {value: user.remember_token, 
									expires: 24.hours.from_now.utc }
		self.current_user = user		
	end

	def current_user=(user)
    	@current_user = user
  	end

  	def current_user
  		@current_user ||= User.find_by_remember_token(cookies[:remember_token])  		
  	end

  	def signed_in?
  		!current_user.nil?  		
  	end

  	def sign_out
  		self.current_user = nil
  		cookies.delete(:remember_token)
  	end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in"
        
      end
      
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/events/_event.html.erb
<li>
	<%= link_to event.title, event, class: "content" %>
	<span class = "desc"><%= event.description %></span>
</li>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :title %><br />
    <%= f.text_field :title %>

    <%= f.label :description %><br />
    <%= f.text_area :description %>

    <%= f.label :venue %><br />
    <%= f.text_field :venue %>

    <%= f.label :start_date %><br />
    <%= f.date_select :start_date, :order =>[:day, :month, :year] %>

        <%= f.label :end_date %><br />
    <%= f.date_select :end_date, class: "datetime-select" %>

    <%= f.submit class: "btn btn-large btn-primary" %>
<% end %>

app/views/events/edit.html.erb
<div class = "row">
	<div class = "span6 offset3">
		<h1>Editing event</h1>

		<%= render 'form' %>
		<%= link_to 'Show', @event, class: "btn"%> |
		<%= link_to 'Back', myevents_path, class: "btn" %>
	</div>
</div>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Description</th>
    <th>Venue</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.user_id %></td>
    <td><%= event.description %></td>
    <td><%= event.venue %></td>
    <td><%= event.end_date %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<div class = "row">
	<div class = "span6 offset3">
		<h1>New event</h1>

		<%= render 'form' %>

		<%= link_to 'Back', myevents_path, class: "btn" %>
	</div>
</div>

app/views/events/show.html.erb
<div class = "row">
  <div class = "span4 offset1">
    <p>
      <b>Title:</b>
      <%= @event.title %>
    </p>

    <p>
      <b>Description:</b>
      <%= @event.description %>
    </p>

    <p>
      <b>Venue:</b>
      <%= @event.venue %>
    </p>

    <p>
      <b>Start date:</b>
      <%= @event.start_date %>
    </p>

    <p>
      <b>End date:</b>
      <%= @event.end_date %>
    </p>


    <%= link_to 'Edit', edit_event_path(@event) %> |
    <%= link_to 'Back', current_user %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer">
	<div class="container">
		<p>&copy; Eventica 2013</p>
		<p class="pull-right">All rights are reserved</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar-wrapper">
	<div class = "container">
		<div class="navbar navbar-inverse">
			<div class="navbar-inner">
				<div class="container">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					<%= link_to "Eventica", root_path, class: "brand" %>
					<div class="nav-collapse">
						<ul class="nav">
							<li><%= link_to "События", '#events' %></li>
							<li><%= link_to "Шаги", steps_path %></li>
							<li><%= link_to "О Нас", about_path %></li>
							<li><%= link_to "Контакты", contacts_path %></li>
						</ul>
						
							<% if signed_in? %>
								<ul class="nav pull-right">
									<li><%= link_to "Users", '#' %></li>
									<li id="fat-menu" class="dropdown">
										<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user[:name] %> <b class="caret"></b></a>
									
										<ul class="dropdown-menu">
											<li><%= link_to "Профиль", current_user %></li>
											<li><%= link_to "Настройки", '#' %></li>
											<li class = "divider"></li>
											<li>
												<%= link_to "Выход", signout_path, method: "delete" %>
											</li>
										</ul>
									</li>
								</ul>
							<% else %>
								<div class="nav pull-right">
									<%= link_to "Регистрация", signup_path, class: "btn btn-primary" %>
									<%= link_to "Вход", signin_path, class: "btn btn-success" %>
								</div>
							<% end %>

						
					</div><!--/.nav-collapse -->
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventica</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<div id="wrap">
		<%= render 'layouts/header' %>

		<div class="container content">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
		</div> <!-- /container -->

		<div id="push"></div>
	</div>
	<%= render 'layouts/footer' %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/_events.html.erb
<div class="event-list span8 offset1">
    <% @events.each do |event| %>
      <div class="event-unit">
        <div class = "e-date">
          <strong><%= event.start_date.strftime("%^a") %></strong>
          <%= event.start_date.strftime("%b%-d").downcase.to_s %>
        </div>
        <h4><%= link_to event.title, event %></h4>
        <p><%= event.description %></p>
      </div>
      <hr class="e-divider">
    <% end %>
</div>

app/views/static_pages/home.html.erb
  <!-- Main hero unit for a primary marketing message or call to action -->
  <div class="hero-unit">
    <h1>Eventica</h1>
    <p>Это сайт с помощью которого вы можете создать мероприятие и продавать билеты на него</p>
    <p><%= link_to "Создать мероприятие", create_path, class: "btn btn-success btn-large" %></p>
  </div>

  <!-- Example row of columns -->
  <div class="row">
  <%= render 'events.html.erb' %> 
    <div class="special span3">
      <div class="adblock">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
      </div>
    </div>
  </div>

  <hr>

app/views/static_pages/steps.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/users/new.html.erb
<div class = "row">
	<div class="span6 offset3">
		<h2>Регистрация</h2>
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name, "Имя" %>
			<%= f.text_field :name %>

			<%= f.label :email, "Электронный адрес" %>
			<%= f.text_field :email %>

			<%= f.label :password, "Пароль" %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Подтверждение пароля" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Зарегестрироваться", class: "btn btn-large btn-primary" %>

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<aside class="span4 offset1">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
			<%= link_to "Новое событие", create_path %>
		</section>
	</aside>
</div>
<div class = "row">
	<div class = "span4 offset1">
		<% if @user.events.any? %>
			<h3>События (<%= @user.events.count %>)</h3> 
			<ul class = "events">
				<%= render @events %>
			</ul>
			<%= will_paginate @events %>
		<% end %>
	</div>
</div>